### ISSUE TITLE
Links with no obvious function

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/RISKy#11]
Currently links to terms and taxon groups, e.g. 
https://www.ris-ky.info/establishment-statuses/established
https://www.ris-ky.info/taxonomy/term/1938
etc.
have no useful content.
Would it be possible for these pages to present actual lists of species' URLs matching these terms? Or, if not, can we just remove all such links (this would include all taxon terms, and all terms within termlists like habitats, establishment status, impacts etc.?

**Comment by johnvanbreda** [comment]
Term pages now have useful links back to the associated species
