### ISSUE TITLE
Species images display issue

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/RISKy#12]
The display of photos within accounts is odd. Photos are not taking up the full area available on the image ribbon. 

See screenshot below:
![image](https://user-images.githubusercontent.com/5985134/105502890-dc540400-5cbd-11eb-9938-548d4bfdd065.png)

**Comment by johnvanbreda** [comment]
Should be sorted now. Not sure why the gallery image display format template had been messed up.

**Comment by sacrevert** [comment]
Thanks John, much appreciated
