### ISSUE TITLE
Collapsed sections broken on website

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/RISKy#15]
@BirenRathod I notice that the "[collapse]" tags on these pages are broken, is that Drupal versioning issue?
https://ris-ky.info/resources
https://ris-ky.info/home

**Comment by BirenRathod** [comment]
@sacrevert Yes, I'm aware that. I just migrated site from Drupal 8 to Drupal 9 now on Pantheon. That collapse feature has not supported by Drupal 9, so I need to implement that and twitter blog too. Twitter blog displays too long on the page. Thanks for letting me know anyway.

**Comment by sacrevert** [comment]
OK, brilliant. Thanks @BirenRathod no great rush for any of this from our end

**Comment by BirenRathod** [comment]
@sacrevert This has resolved now, so you can close it.

**Comment by sacrevert** [comment]
Thanks!
