### ISSUE TITLE
CyDAS view on phone or tablet

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/RISKy#6]
Not sure whether this is best done by Biren or John:

>On a phone when the content resizes the accounts appear below the taxon tree selector. However, when you choose a species the screen does not jump down to the account that has loaded. This makes one feel that nothing has happened. Is this fixable?

**Comment by johnvanbreda** [comment]
I've managed to make it automatically scroll. I don't have permissions to close the issue so please close if OK.
