### ISSUE TITLE
Automate GBIF data flow

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/RISKy#8]
Links to 
https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues/5
https://github.com/BiologicalRecordsCentre/ABLE/issues/6

Awaiting prioritization.  John's summary:
Move to more automated data flow requiring:

- Use the iRecord Exports system to generate a new Darwin Core archive.
- Use the IPT to add the file to the existing resource, overwriting the old files.
- Check the mappings (should be OK but I had a problem when I did this which I think was me, but just to be sure).
- Publish the new version using the IPT.

I suspect that we could implement a clever solution which runs on the IPT server to re-build the source file and place it in the IPT data directory on a schedule. The IPT can be configured to periodically publish. This would be a few days work I suspect.

**Comment by johnvanbreda** [comment]
New tool for auto-generation of DwCA files now in testing.

**Comment by sacrevert** [comment]
Closing this as I think it is adequately dealt with elsewhere
